const ApiEndpoints = {
  LOGIN: "auth/login",
  USERS_LIST: "users/list",
  USERS_DETAIL: "users/detail",
  USERS_ADD: "users/add",
  USERS_EDIT: "users/edit",
  NEWS_LIST: "news/list",
  NEWS_DETAIL: "news/detail",
  NEWS_ADD: "news/add",
  NEWS_EDIT: "news/edit",
  NEWS_TEST_NOTIFICATION: "news/notification",
  NEWS_REMOVE: "news/remove",
  USEFUL_INFO_LIST: "useful-info/list",
  USEFUL_INFO_DETAIL: "useful-info/detail",
  USEFUL_INFO_ADD: "useful-info/add",
  USEFUL_INFO_EDIT: "useful-info/edit",
  USEFUL_INFO_REMOVE: "useful-info/remove",
  INCIDENTS_LIST: "incidents/list",
  INCIDENTS_DETAIL: "incidents/detail",
  INCIDENTS_ADD: "incidents/add",
  INCIDENTS_UPDATE_STATUS: "incidents/updateStatus",
  GET_IMAGE_UPLOAD_TOKEN: "incidents/getImageUploadToken",
};
export default ApiEndpoints;
